---
- name: Run commands on remote cEOS-lab device
  hosts: ceos
  connection: network_cli
  gather_facts: no
  vars:
    ansible_python_interpreter: "python"
    ansible_network_os: 'eos'
  tasks:

    - name: Execute Arista EOS command
      eos_command:
        commands: show version
      register: version

    - name: Display result
      debug:
        msg: "{{ version.stdout }}"

- name: Run commands on remote cEOS-lab device
  hosts: ceos
  connection: netconf
  gather_facts: no
  vars:
    ansible_python_interpreter: "python"
    ansible_network_os: 'eos'
  tasks:

    - name: Get list of availables YANG schema
      netconf_get:
        display: pretty
        filter: |
            <netconf-state xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring">
                <schemas>
                    <schema/>
                </schemas>
            </netconf-state>
        lock: never
      register: list_of_schemas

    - name: Display list of availables YANG schema
      debug:
        msg: "{{ list_of_schemas.output }}"